abatix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("masters.urls")),
    path("stock/", include("stock.urls")),
    path("sales/", include("sales.urls")),
    path("vouchers/", include("vouchers.urls"))
]

sales/urls.py
from django.urls import path
from .views import (
    InvoiceDetailView, InvoiceListView, InvoiceCreateView, InvoiceUpdateView,
    HomeSaleListView, HomeSaleCreateView, HomeSaleUpdateView,
    AdvanceDetailView, AdvanceListView, AdvanceCreateView, AdvanceUpdateView, AdvanceFetchAjax
)

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name="invoices"),
    path("invoices/new", InvoiceCreateView.as_view(), name="invoice_new"),
    path("invoices/<int:pk>/edit", InvoiceUpdateView.as_view(), name="invoice_edit"),
    path("invoices/<int:pk>/print", InvoiceDetailView.as_view(), name="invoice_print"),
    path("advances", AdvanceListView.as_view(), name="advances"),
    path("advances/new", AdvanceCreateView.as_view(), name="advance_new"),
    path("advances/<int:pk>/edit", AdvanceUpdateView.as_view(), name="advance_edit"),
    path("advances/<int:pk>/print", AdvanceDetailView.as_view(), name="advance_print"),
    path("_fetch_advance", AdvanceFetchAjax.as_view(), name="fetch_advance"),   
    path("home_sales", HomeSaleListView.as_view(), name="home_sales"),
    path("home_sales/new", HomeSaleCreateView.as_view(), name="home_sale_new"),
    path("home_sales/<int:pk>/edit", HomeSaleUpdateView.as_view(), name="home_sale_edit"),
]

sales/models/advance.py
from django.db import models
from masters.models import Customer, GST_State
from .invoice import Invoice
from django.urls import reverse

import datetime

def get_advance_number():
    today = datetime.date.today()
    last_april_date = datetime.date(today.year, 4, 1)
    if last_april_date > today:
        last_april_date = last_april_date.replace(year=today.year - 1)
    return Advance.objects.filter(date__gte = last_april_date).count() + 1

def get_gst_state():
    return GST_State.objects.get(state="Maharashtra")

class Advance(models.Model):
    advance_number = models.IntegerField(default=get_advance_number, verbose_name='Adv. No.')
    date = models.DateField(default=datetime.date.today)
    state = models.ForeignKey(GST_State, on_delete=models.CASCADE, related_name='advances', default=get_gst_state)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="advances")
    redeemed = models.BooleanField(default=False)

    @property
    def amount(self):
        sum = self.payments.aggregate(models.Sum('amount', default=0, output_field=models.DecimalField()))["amount__sum"]
        return round(sum, 2)

    def __str__(self):
        return f"{self.advance_number}"

    def get_absolute_url(self):
        return reverse("advances")

sales/models/home_sale.py
from django.db import models
from stock.models import Product
from django.urls import reverse

import datetime

class Home_Sale(models.Model):
    date = models.DateField(default=datetime.date.today)

    @property
    def gross_weight(self):
        products_sum = self.products.aggregate(models.Sum('product__gross_weight', default=0, output_field=models.DecimalField()))["product__gross_weight__sum"]
        return round(products_sum, 3)

    @property
    def less_weight(self):
        products_sum = self.products.aggregate(models.Sum('product__less_weight', default=0, output_field=models.DecimalField()))["product__less_weight__sum"]
        return round(products_sum, 3)

    @property
    def net_weight(self):
        products_sum = self.products.aggregate(models.Sum('product__net_weight', default=0, output_field=models.DecimalField()))["product__net_weight__sum"]
        return round(products_sum, 3)

    def __str__(self):
        return f"{self.date}"

    def get_absolute_url(self):
        return reverse('home_sales')

class Home_Sale_Product(models.Model):
    home_sale = models.ForeignKey(Home_Sale, on_delete=models.CASCADE, related_name="products")
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name="home_sale")

    def delete(self, *args, **kwargs):
        self.product.sold = False
        self.product.save()
        return super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.product.sold = True
        self.product.save()
        super().save(*args, **kwargs)

stock/models.py
from django.db import models
from masters.models import Metal, Purity, Type, Category, Stud_Type, Unit
from django.urls import reverse

import datetime

# Create your models here.
class Vendor(models.Model):
    name = models.CharField(max_length=64)
    firm = models.CharField(max_length=64, blank=True)
    contact = models.CharField(max_length=16, blank=True)
    email = models.EmailField(blank=True)
    old_id = models.CharField(max_length=16, blank=True)
    old_description = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return f"{self.name} {self.firm} ({self.old_id})"

class Product(models.Model):
    register_id = models.CharField(max_length=16,blank=True, null=True, verbose_name='Register')
    metal = models.ForeignKey(Metal, on_delete=models.CASCADE, related_name="products")
    purity = models.ForeignKey(Purity, on_delete=models.CASCADE, related_name="products")
    type = models.ForeignKey(Type, on_delete=models.CASCADE, related_name="products")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    pieces = models.IntegerField(default=1)
    gross_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Gross Wt.")
    studs_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Studs Wt.")
    less_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Less Wt.")
    net_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Net Wt.")

    rate = models.DecimalField(max_digits=16, decimal_places=2)
    calculation = models.CharField(max_length=32, blank=False, default="Making Charges", choices=[
    ("Making Charges", "Making Charges"),
    ("Wastage", "Wastage"),
    ("MRP", "MRP")
    ])
    making_charges = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True, verbose_name='Making')
    wastage = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    mrp = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True, verbose_name="MRP")

    description = models.TextField(blank=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name="products")
    purchase_date = models.DateField(default=datetime.date.today, verbose_name="Date")
    lot_number = models.IntegerField(blank=True, null=True, verbose_name="Lot Number")
    design_code = models.CharField(max_length=32, blank=True, verbose_name='Design Code')
    old_id = models.CharField(max_length=16, blank=True, verbose_name='Jilaba ID')
    sold = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk} - {self.purity.purity} {self.metal.metal} {self.category.category}"

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk' : self.pk})

class Stud(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="studs")
    type = models.ForeignKey(Stud_Type, on_delete=models.CASCADE, related_name="studs")
    less = models.BooleanField(default=False)
    colour = models.CharField(max_length=64, blank=True)
    shape = models.CharField(max_length=64, blank=True)
    quantity = models.IntegerField(default=1)
    weight = models.DecimalField(max_digits=16, decimal_places=3)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name="studs")
    rate = models.DecimalField(max_digits=16, decimal_places=2)
    value = models.DecimalField(max_digits=16, decimal_places=2)

    def __str__(self):
        return f"{self.type.type}"

sales/forms/advance.py
from django import forms
from sales.models import Advance, Payment
from masters.models import Customer

class AdvanceForm(forms.ModelForm):
    class Meta:
        model = Advance
        fields = ('advance_number', 'date', 'state')
        widgets = {
            'advance_number': forms.TextInput(attrs={'readonly':True}),
            'date': forms.DateInput(attrs={'type':'date'})
        }

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('contact', 'name', 'firm', 'gst', 'pan', 'aadhar', 'email', 'address', 'city', 'pincode')

    def clean_name(self):
        return self.cleaned_data['name'].title()
    
    def clean_firm(self):
        return self.cleaned_data['firm'].title()
    
    def clean_city(self):
        return self.cleaned_data['city'].title()

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        exclude = ('advance', 'invoice')
        widgets = {
            'date': forms.DateInput(attrs={'type':'date'})
        }

PaymentFormSet = forms.inlineformset_factory(Advance, Payment, exclude=('advance','invoice',), extra=0, can_delete=True)

sales/forms/home_sale.py
from django import forms
from sales.models import Home_Sale, Home_Sale_Product

class HomeSaleForm(forms.ModelForm):
    class Meta:
        model = Home_Sale
        fields = ('date',)
        widgets = {
            'date': forms.DateInput(attrs={'type':'date'})
        }
widgets = {
    'product': forms.NumberInput(attrs={
        'placeholder':"Add",
        'onfocus':'addRow(this)',
        'oninput':"validateID(this, '/stock/_fetch_product')"
    })
}
ProductFormSet = forms.inlineformset_factory(Home_Sale, Home_Sale_Product, fields=('product',), extra=0, can_delete=True, widgets=widgets)

sales/views/advance.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, AccessMixin
from sales.models import Advance
from masters.models import Customer
from sales.forms.advance import AdvanceForm, PaymentFormSet, PaymentForm, CustomerForm
from django.forms.models import model_to_dict
from django.http import JsonResponse

from django.db.models import Q

import json
from num2words import num2words
import datetime

class AdvanceBaseView(LoginRequiredMixin, PermissionRequiredMixin, AccessMixin):
    permission_required = ("sales.view_advance", "sales.add_advance", "sales.change_advance", "sales.delete_advance")
    raise_exception = True
    permission_denied_message = "You do not have permission to access Advance details."

class AdvanceDetailView(AdvanceBaseView, DetailView):
    model = Advance
    permission_required = "sales.view_advance"
    template_name = "sales/advance_print.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        amount_words = num2words(self.object.amount, to="cardinal", lang='en_IN').title()
        amount_words = amount_words.replace("AND", "&")
        today = datetime.date.today()
        context["amount_words"] = amount_words
        last_april_date = datetime.date(today.year, 4, 1)
        if last_april_date > today:
            last_april_date = last_april_date.replace(year=today.year - 1)
            context["financial_year"] = f"{last_april_date.year}-{today.strftime('%y')}"
        else:
            context["financial_year"] = f"{today.year}-{today.replace(year=today.year+1).strftime('%y')}"
        return context

class AdvanceListView(AdvanceBaseView, ListView):
    permission_required = "sales.view_advance"
    template_name = "sales/advances.html"
    queryset = Advance.objects.order_by("-advance_number")
    context_object_name = "advances"

    def get_queryset(self):
        today = datetime.date.today()
        last_april_date = datetime.date(today.year, 4, 1)
        if last_april_date > today:
            last_april_date = last_april_date.replace(year=today.year - 1)
        
        start_date = self.request.GET.get("start_date", last_april_date.strftime('%Y-%m-%d'))
        end_date = self.request.GET.get("end_date", today.strftime('%Y-%m-%d'))
        search = self.request.GET.get("search", "")
        queryset = Advance.objects.filter(Q(customer__name__icontains = search) | Q(customer__firm__icontains=search), date__gte=start_date, date__lte=end_date, 
                                          ).order_by("-advance_number")
        return queryset
    
    def get_context_data(self, **kwargs):
        today = datetime.date.today()
        last_april_date = datetime.date(today.year, 4, 1)
        if last_april_date > today:
            last_april_date = last_april_date.replace(year=today.year - 1)
        context = super().get_context_data(**kwargs)
        context['start_date'] = self.request.GET.get("start_date", last_april_date.strftime('%Y-%m-%d'))
        context["end_date"] = self.request.GET.get("end_date", today.strftime('%Y-%m-%d'))
        context["search"] = self.request.GET.get("search", "")
        return context

class AdvanceCreateView(AdvanceBaseView, CreateView):
    model = Advance
    permission_required = "sales.add_advance"
    template_name = "sales/advance_form.html"
    form_class = AdvanceForm

    def form_valid(self, form):
        context = self.get_context_data()
        context["customer_form"] = CustomerForm(self.request.POST)
        context["payment_formset"] = PaymentFormSet(self.request.POST)
        if context["customer_form"].is_valid() and context["payment_formset"].is_valid():
            try:
                if context["customer_form"].cleaned_data['contact'] != "":
                    cust = Customer.objects.get(contact = context["customer_form"].cleaned_data['contact'])
                    context["customer_form"] = CustomerForm(self.request.POST, instance=cust)
                    customer = context["customer_form"].save()
                else:
                    customer = context["customer_form"].save()
            except:
                customer = context["customer_form"].save()
            form.instance.customer = customer
            self.object = form.save()
            context["payment_formset"].instance = self.object
            context["payment_formset"].save()
            return redirect(self.get_success_url())
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["payment_formset"] = PaymentFormSet()
        context["payment_form"] = PaymentForm(label_suffix="")
        context["customer_form"] = CustomerForm(label_suffix="")
        try:
            context["id"] = Advance.objects.order_by("pk").last().id + 1
        except:
            context["id"] = 1
        return context
    
    def get_form_kwargs(self, **kwargs):
        form_kwargs = super(AdvanceCreateView, self).get_form_kwargs(**kwargs)
        form_kwargs["label_suffix"] = ""
        return form_kwargs

class AdvanceUpdateView(AdvanceBaseView, UpdateView):
    model = Advance
    permission_required = "sales.change_advance"
    template_name = "sales/advance_form.html"
    form_class = AdvanceForm

    def form_valid(self, form):
        context = self.get_context_data()
        context["customer_form"] = CustomerForm(self.request.POST, instance=self.object.customer)
        context["payment_formset"] = PaymentFormSet(self.request.POST, instance=self.object)
        if context["customer_form"].is_valid() and context["payment_formset"].is_valid():
            try:
                if context["customer_form"].cleaned_data['contact'] != "":
                    cust = Customer.objects.get(contact = context["customer_form"].cleaned_data['contact'])
                    context["customer_form"] = CustomerForm(self.request.POST, instance=cust)
                    customer = context["customer_form"].save()
                else:
                    customer = context["customer_form"].save()
            except:
                customer = context["customer_form"].save()
            form.instance.customer = customer
            self.object = form.save()
            context["payment_formset"].save()
            return redirect(self.get_success_url())
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["payment_formset"] = PaymentFormSet(instance=self.object)
        context["payment_form"] = PaymentForm(label_suffix="")
        context["customer_form"] = CustomerForm(label_suffix="", instance=self.object.customer)
        context["id"] = self.object.id
        return context
    
class AdvanceFetchAjax(AdvanceBaseView, View):
    permission_required = "sales.view_advance"
    def post(self, request, *args, **kwargs):
        id = json.loads(request.body)["id"]
        try:
            advance = Advance.objects.get(pk=id)
            advance_dict = model_to_dict(advance)
            advance_dict['name'] = advance.customer.name
            advance_dict['amount'] = advance.amount
        except:
            advance_dict = {}
        return JsonResponse(advance_dict)

sales/templates/sales/invoice_form.html
{% extends "masters/layout.html" %}
{% load static %}

{% block title %} Invoice Form {% endblock %}

{% block link %}
  <link rel="stylesheet" href="{% static 'sales/css/invoice_form.css' %}">
  <script src="{% static 'sales/js/invoice_form.js' %}" charset="utf-8"></script>
{% endblock %}

{% block errors %}
  {% for key,errors in form.errors.items  %}
    {% for error in errors %}
      <div class="error_box">
        <img src="{% static 'masters/svg/cross.svg' %}" title="Error" class="cross">
        <h2>Error</h2>
        <h3>{{ error }}</h3>
        <img src="{% static 'masters/svg/close.svg' %}" title="Close" class="close" onclick="this.parentElement.style.display = 'none'">
      </div>
    {% endfor %}
  {% endfor %}
{% endblock %}

{% block body %}
</div>

<form action="{{request.path }}" method="post">
  {% csrf_token %}

  <div id="invoice_box">
    <div>
      <label for="id_id">I.D.</label>
      <input type="text" value="{{ id }}" readonly>
    </div>
    {{ form.as_div }}
  </div>

  <div id="customer_box">
    {{ customer_form.as_div }}
  </div>

  <div id="products_box">
    {{ product_formset.management_form }}
    {{ untagged_formset.management_form }}
    <h1>Products</h1>
    <table class="products_table" id="products_table">
      <thead>
        <tr>
          <th>Tagged</th>
          <th>Gross Wt.</th>
          <th>Net Wt.</th>
          <th>Subtotal</th>
          <th>Tax</th>
          <th>Total</th>
          <th hidden></th>
          <th></th>
        </tr>
      </thead>
  
      <tbody>
        {% for product in product_formset %}
          <tr>
            <td><p id="id_metal_table">{{ product.instance.product.metal }}</p> <p id="id_category_table">{{ product.instance.product.category }}</p></td>
            <td id="id_gross_weight_table">{{ product.instance.product.gross_weight }}</td>
            <td id="id_net_weight_table">{{ product.instance.product.net_weight }}</td>
            <td id="id_subtotal_table">{{ product.subtotal.value }}</td>
            <td id="id_tax_table">{{ product.sgst.value | add:product.cgst.value |add:product.igst.value |add:product.tcs.value }}</td>
            <td id="id_total_table">{{ product.total.value }}</td>
            <td hidden>
              {{ product.as_div }}
              <input type="number" name="id-__prefix__-tax" id="" value="{{ product.sgst.value | add:product.cgst.value |add:product.igst.value |add:product.tcs.value }}" hidden>
            </td>
            <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteProductRow(this)"></td>
          </tr>
        {% endfor %}

        <tr style="display: none;">
          <td><p id="id_metal_table"><p> <p id="id_category_table"></p></td>
          <td id="id_gross_weight_table"></td>
          <td id="id_net_weight_table"></td>
          <td id="id_subtotal_table"></td>
          <td id="id_tax_table"></td>
          <td id="id_total_table"></td>
          <td hidden>
            {{ product_formset.empty_form.as_div }}
            <input type="number" name="id-__prefix__-tax" id="" hidden>
          </td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteProductRow(this)" style="display: none;"></td>
        </tr>
      </tbody>
    </table>

    <table class="products_table" id="untagged_table">
      <thead>
        <tr>
          <th>Untagged</th>
          <th>Gross Wt.</th>
          <th>Net Wt.</th>
          <th>Subtotal</th>
          <th>Tax</th>
          <th>Total</th>
          <th hidden></th>
          <th></th>
        </tr>
      </thead>
  
      <tbody>
        {% for product in untagged_formset %}
          <tr>
            <td><p id="id_metal_table">{{ product.instance.metal }}</p> <p id="id_category_table">{{ product.instance.category }}</p></td>
            <td id="id_gross_weight_table">{{ product.gross_weight.value }}</td>
            <td id="id_net_weight_table">{{ product.net_weight.value }}</td>
            <td id="id_subtotal_table">{{ product.subtotal.value }}</td>
            <td id="id_tax_table">{{ product.sgst.value | add:product.cgst.value |add:product.igst.value |add:product.tcs.value }}</td>
            <td id="id_total_table">{{ product.total.value }}</td>
            <td hidden>
              {{ product.as_div }}
              <input type="number" name="id-__prefix__-tax" id="" hidden value="{{ product.sgst.value | add:product.cgst.value |add:product.igst.value |add:product.tcs.value }}">
            </td>
            <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteProductRow(this)"></td>
          </tr>
        {% endfor %}

        <tr style="display: none;">
          <td><p id="id_metal_table"></p> <p id="id_category_table"></p></td>
          <td id="id_gross_weight_table"></td>
          <td id="id_net_weight_table"></td>
          <td id="id_subtotal_table"></td>
          <td id="id_tax_table"></td>
          <td id="id_total_table"></td>
          <td hidden>
            {{ untagged_formset.empty_form.as_div }}
            <input type="number" name="id-__prefix__-tax" id="" hidden>
          </td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteProductRow(this)" style="display: none;"></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div id="advances_box">
    {{ advance_formset.management_form }}
    <h1>Advances</h1>
    <table id="advances_table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Date</th>
          <th>Name</th>
          <th>Amount</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        {% for advance in advance_formset %}
          <tr>
            <td id="id_advance_table">{{ advance.instance.advance.advance_number }}</td>
            <td id="id_date_table">{{ advance.instance.advance.date |date:'Y-m-d' }}</td>
            <td id="id_name_table">{{ advance.instance.advance.customer.name }}</td>
            <td id="id_amount_table">{{ advance.instance.advance.amount }}</td>
            <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteAdvanceRow(this)"></td>
            <td hidden>
              {{ advance.as_div }}
              <div><input name="name-__prefix__-date" value="{{ advance.instance.advance.date |date:'Y-m-d' }}"></div>
              <div><input name="name-__prefix__-name" value="{{ advance.instance.advance.customer.name }}"></div>
              <div><input name="name-__prefix__-amount" value="{{ advance.instance.advance.amount }}"></div>
            </td>
          </tr>
        {% endfor %}
        <tr style="display: none;">
          <td id="id_advance_table"></td>
          <td id="id_date_table"></td>
          <td id="id_name_table"></td>
          <td id="id_amount_table"></td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteAdvanceRow(this)" style="display:none;"></td>
          <td hidden>
            {{ advance_formset.empty_form.as_div }}
            <div><input name="name-__prefix__-date" value=""></div>
            <div><input name="name-__prefix__-name" value=""></div>
            <div><input name="name-__prefix__-amount" value=""></div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div id="payments_box">
    {{ payment_formset.management_form }}
    <h1>Payments</h1>

    <table id="payments_table">
      <thead>
        <tr>
          <th>#</th>
          <th>Method</th>
          <th>Date</th>
          <th>Amount</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        {% for payment in payment_formset %}
          <tr>
            <td id="id_serial_number_table">{{ forloop.counter }}</td>
            <td id="id_method_table">{{ payment.method.value }}</td>
            <td id="id_date_table">{{ payment.date.value |date:"Y-m-d" }}</td>
            <td id="id_amount_table">{{ payment.amount.value }}</td>
            <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deletePaymentRow(this)"></td>
            <td hidden>
              {{ payment.as_div }}
            </td>
          </tr>
        {% endfor %}
        <tr style="display: none;">
          <td id="id_serial_number_table"></td>
          <td id="id_method_table"></td>
          <td id="id_date_table"></td>
          <td id="id_amount_table"></td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deletePaymentRow(this)" style="display: none;"></td>
          <td hidden>
            {{ payment_formset.empty_form.as_div }}
          </td>
        </tr>
      </tbody>

    </table>
  </div>

  <div id="totals_box">
    <div>
      <p>Weight</p>
      <span id="id_net_weight_total"></span>
    </div>
    <div>
      <p>Subtotal</p>
      <span id="id_subtotal_total"></span>
    </div>
    <div>
      <p>Tax</p>
      <span id="id_tax_total"></span>
    </div>
    <div>
      <p>Total</p>
      <span id="id_total_total"></span>
    </div>
    <div>
      <p>Total Payments</p>
      <span id="id_payment_total"></span>
    </div>
  </div>

  <a href="{% url 'invoices' %}"><button type="button" class="new_button" id="invoice_cancel">Cancel</button></a>
  <button type="submit" class="submit_button" id="invoice_submit">Submit</button>
</form>

<div id="product_subform">
  <button type="button" class="new_button" id="product_new" onclick="newProductRow(this)">New</button>
  <form action="javascript:submitProductRow(this)" hidden id="products_subform">
    <div>
      <input type="radio" name="radio_type" id="id_tagged" value="tagged" oninput="switchProductFields(this)" required>
      <label for="id_tagged">Tagged</label>
      <input type="radio" name="radio_type" id="id_untagged" value="untagged" oninput="switchProductFields(this)">
      <label for="id_untagged">Untagged</label>
    </div>

    <div>
      <label for="id_product">ID</label>
      <input type="number" id="id_product" name="product" oninput="validateProductID(this)">
    </div>
    
    {{ untagged_form.as_div }}

    
    <button type="reset" class="clear_button" id="product_clear">Clear</button>
    <button type="submit" class="submit_button" id="product_submit">Save</button>
  </form>
</div>

<div id="advance_subform">
  <button type="button" class="new_button" id="advance_new" onclick="newAdvanceRow(this)">New</button>
  <form action="javascript:submitAdvanceRow(this)" hidden id="advances_subform" onchange="validateAdvanceID(this)">
    {{ invoice_advance_form.advance }}
    <input type="text" name="date" id="id_date" hidden>
    <input type="text" name="name" id="id_name" hidden>
    <input type="text" name="amount" id="id_amount" hidden>
    <button type="submit" class="submit_button" id="advance_submit">Save</button>
  </form>
</div>

<div id="payment_subform">
  <button type="button" class="new_button" id="payment_new" onclick="newPaymentRow(this)">New</button>
  <form action="javascript:submitPaymentRow(this)" hidden id="payments_subform">
    <div id="payment_subform_div">
      {{ payment_form.as_div }}
    </div>
    <button type="reset" class="clear_button" id="payment_clear">Clear</button>
    <button type="submit" class="submit_button" id="payment_submit">Save</button>
  </form>
</div>

{% endblock %}