abatix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("masters.urls")),
    path("stock/", include("stock.urls")),
    path("sales/", include("sales.urls")),
    path("vouchers/", include("vouchers.urls"))
]

sales/urls.py
from django.urls import path
from .views import (
    InvoiceDetailView, InvoiceListView, InvoiceCreateView, InvoiceUpdateView,
    HomeSaleListView, HomeSaleCreateView, HomeSaleUpdateView,
    AdvanceDetailView, AdvanceListView, AdvanceCreateView, AdvanceUpdateView, AdvanceFetchAjax
)

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name="invoices"),
    path("invoices/new", InvoiceCreateView.as_view(), name="invoice_new"),
    path("invoices/<int:pk>/edit", InvoiceUpdateView.as_view(), name="invoice_edit"),
    path("invoices/<int:pk>/print", InvoiceDetailView.as_view(), name="invoice_print"),
    path("advances", AdvanceListView.as_view(), name="advances"),
    path("advances/new", AdvanceCreateView.as_view(), name="advance_new"),
    path("advances/<int:pk>/edit", AdvanceUpdateView.as_view(), name="advance_edit"),
    path("advances/<int:pk>/print", AdvanceDetailView.as_view(), name="advance_print"),
    path("_fetch_advance", AdvanceFetchAjax.as_view(), name="fetch_advance"),   
    path("home_sales", HomeSaleListView.as_view(), name="home_sales"),
    path("home_sales/new", HomeSaleCreateView.as_view(), name="home_sale_new"),
    path("home_sales/<int:pk>/edit", HomeSaleUpdateView.as_view(), name="home_sale_edit"),
]

stock/urls.py
from django.urls import path
from .views import ProductDetailView, ProductFetchAjax, ProductCreateView, ProductUpdateView, PrintTag

urlpatterns = [
    path("<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("_fetch_product", ProductFetchAjax.as_view(), name="fetch_product"),
    path("new", ProductCreateView.as_view(), name="product_new"),
    path("<int:pk>/edit", ProductUpdateView.as_view(), name="product_edit"),
    path("<int:pk>/print_tag", PrintTag, name="print_tag"),
]

masters/models/product.py
from django.db import models
from .gst import HSN

class Metal(models.Model):
    metal = models.CharField(max_length=32, unique=True)
    symbol = models.CharField(max_length=32, blank=True)
    colour = models.CharField(max_length=32, blank=True)
    melting_point = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    boiling_point = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    density = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return self.metal

class Purity(models.Model):
    class Meta:
        verbose_name = "Purity"
        verbose_name_plural = "Purities"
    purity = models.DecimalField(max_digits=16, decimal_places=2, unique=True)
    karatage = models.CharField(max_length=32, blank=True)
    display_name = models.CharField(max_length=32, blank=True)

    def __str__(self):
        return f"{self.purity}"

class Type(models.Model):
    type = models.CharField(max_length=64, unique=True)
    hsn = models.ForeignKey(HSN, on_delete=models.CASCADE, related_name="types")
    abbreviation = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return self.type

class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    category = models.CharField(max_length=64, unique=True)
    abbreviation = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return self.category

class Stud_Type(models.Model):
    class Meta:
        verbose_name = "Stud Type"
        verbose_name_plural = "Stud Types"

    type = models.CharField(max_length=64, unique=True)
    latin_name = models.CharField(max_length=64, blank=True)
    hindi_name = models.CharField(max_length=64, blank=True)
    precious = models.BooleanField(default=False)
    abbreviation = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return self.type

class Unit(models.Model):
    unit = models.CharField(max_length=64, unique=True)
    symbol = models.CharField(max_length=8)
    value_gram = models.DecimalField(max_digits=16, decimal_places=2)

    def __str__(self):
        return self.symbol

stock/models.py
from django.db import models
from masters.models import Metal, Purity, Type, Category, Stud_Type, Unit
from django.urls import reverse

import datetime

# Create your models here.
class Vendor(models.Model):
    name = models.CharField(max_length=64)
    firm = models.CharField(max_length=64, blank=True)
    contact = models.CharField(max_length=16, blank=True)
    email = models.EmailField(blank=True)
    old_id = models.CharField(max_length=16, blank=True)
    old_description = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return f"{self.name} {self.firm} ({self.old_id})"

class Product(models.Model):
    register_id = models.CharField(max_length=16,blank=True, null=True, verbose_name='Register')
    metal = models.ForeignKey(Metal, on_delete=models.CASCADE, related_name="products")
    purity = models.ForeignKey(Purity, on_delete=models.CASCADE, related_name="products")
    type = models.ForeignKey(Type, on_delete=models.CASCADE, related_name="products")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    pieces = models.IntegerField(default=1)
    gross_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Gross Wt.")
    studs_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Studs Wt.")
    less_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Less Wt.")
    net_weight = models.DecimalField(max_digits=16, decimal_places=3, verbose_name="Net Wt.")

    rate = models.DecimalField(max_digits=16, decimal_places=2)
    calculation = models.CharField(max_length=32, blank=False, default="Making Charges", choices=[
    ("Making Charges", "Making Charges"),
    ("Wastage", "Wastage"),
    ("MRP", "MRP")
    ])
    making_charges = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True, verbose_name='Making')
    wastage = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    mrp = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True, verbose_name="MRP")

    description = models.TextField(blank=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name="products")
    purchase_date = models.DateField(default=datetime.date.today, verbose_name="Date")
    lot_number = models.IntegerField(blank=True, null=True, verbose_name="Lot Number")
    design_code = models.CharField(max_length=32, blank=True, verbose_name='Design Code')
    old_id = models.CharField(max_length=16, blank=True, verbose_name='Jilaba ID')
    sold = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk} - {self.purity.purity} {self.metal.metal} {self.category.category}"

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk' : self.pk})

class Stud(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="studs")
    type = models.ForeignKey(Stud_Type, on_delete=models.CASCADE, related_name="studs")
    less = models.BooleanField(default=False)
    colour = models.CharField(max_length=64, blank=True)
    shape = models.CharField(max_length=64, blank=True)
    quantity = models.IntegerField(default=1)
    weight = models.DecimalField(max_digits=16, decimal_places=3)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name="studs")
    rate = models.DecimalField(max_digits=16, decimal_places=2)
    value = models.DecimalField(max_digits=16, decimal_places=2)

    def __str__(self):
        return f"{self.type.type}"

stock/forms.py
from django.forms import ModelForm, inlineformset_factory, DateInput, NumberInput
from .models import Product, Stud

class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('sold',)

class TagDetailsForm(ModelForm):
    class Meta:
        model = Product
        fields = ('purchase_date', 'lot_number', 'old_id', 'register_id', 'design_code')
        widgets = {
            'purchase_date': DateInput(attrs={'type':'date'}),
        }

class MetalDetailsForm(ModelForm):
    class Meta:
        model = Product
        fields = ('metal', 'purity', 'type', 'category', 'description')

class ProductDetailsForm(ModelForm):
    class Meta:
        model = Product
        fields = ('vendor', 'pieces', 'gross_weight', 'studs_weight', 'less_weight', 'net_weight')
        widgets = {
            'studs_weight': NumberInput(attrs={'readonly': True}),
            'less_weight': NumberInput(attrs={'readonly': True}),
            'net_weight': NumberInput(attrs={'readonly': True})
        }

class MakingDetailsForm(ModelForm):
    class Meta:
        model = Product
        fields = ('rate', 'making_charges', 'wastage', 'mrp')

class StudForm(ModelForm):
    class Meta:
        model = Stud
        exclude = ('product',)

StudFormSet = inlineformset_factory(Product, Stud, fields='__all__', extra=0, can_delete=True)

stock/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, AccessMixin
from .models import Product, Stud
from masters.models import Unit
from django.forms.models import model_to_dict
from django.http import JsonResponse
from .forms import ProductForm, StudFormSet, StudForm, TagDetailsForm, MetalDetailsForm, ProductDetailsForm, MakingDetailsForm
from django.core import serializers

from .tag import PrintTag
import json

# Create your views here.
class ProductBaseView(LoginRequiredMixin, PermissionRequiredMixin, AccessMixin):
    permission_required = ("stock.view_product", "stock.add_product", "stock.change_product", "stock.delete_product")
    raise_exception = True
    permission_denied_message = "You do not have permission to access Stock details."


class ProductDetailView(ProductBaseView, DetailView):
    queryset = Product.objects.filter(sold=False).order_by("pk")
    permission_required = "stock.view_product"
    template_name = "stock/product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["first_id"] = self.queryset.first().id
        context["last_id"] = self.queryset.last().id
        return context

    def post(self, request, *args, **kwargs):
        if not self.queryset.exists(): # If table empty or all products sold
            return redirect("product_new")
        if kwargs["pk"] == 0: # The goto product implementation
            return redirect("product_detail", pk=request.POST["id"])
        try:
            return self.get(request, *args, **kwargs)
        except:
            if "next" in request.POST: # The next button implementation
                temp_qs = self.queryset.filter(id__gt = kwargs["pk"])
                if temp_qs.exists():
                    return redirect("product_detail", pk=temp_qs.first().id)
            elif "previous" in request.POST: # The previous button implementation
                temp_qs = self.queryset.filter(id__lt = kwargs["pk"])
                if temp_qs.exists():
                    return redirect("product_detail", pk=temp_qs.last().id)
        return self.get(request, *args, **kwargs)

class ProductFetchAjax(ProductBaseView, View):
    permission_required = "stock.view_product"
    def post(self, request, *args, **kwargs):
        id = json.loads(request.body)["id"]
        try:
            product = Product.objects.get(pk=id)
            product_dict = model_to_dict(product)
        except:
            product_dict = {}
        return JsonResponse(product_dict)

class ProductCreateView(ProductBaseView, CreateView):
    model = Product
    permission_required = "stock.add_product"
    template_name = "stock/product_form.html"
    form_class = ProductForm

    def form_valid(self, form):
        context = self.get_context_data()
        context["formset"] = StudFormSet(self.request.POST)
        if context["formset"].is_valid():
            self.object = form.save()
            context["formset"].instance = self.object
            context["formset"].save()
            return redirect(self.get_success_url())
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag_details_form"] = TagDetailsForm(label_suffix="")
        context["metal_details_form"] = MetalDetailsForm(label_suffix="")
        context["product_details_form"] = ProductDetailsForm(label_suffix="")
        context["making_details_form"] = MakingDetailsForm(label_suffix="")
        context["formset"] = StudFormSet()
        context["stud_form"] = StudForm(label_suffix="")
        context["units"] = serializers.serialize("json", Unit.objects.all())
        try:
            context["id"] = Product.objects.order_by("pk").last().id + 1
        except:
            context["id"] = 1
        return context

class ProductUpdateView(ProductBaseView, UpdateView):
    model = Product
    permission_required = "stock.change_product"
    template_name = "stock/product_form.html"
    form_class = ProductForm
    queryset = Product.objects.filter(sold=False).order_by("pk")

    def form_valid(self, form):
        context = self.get_context_data()
        context["formset"] = StudFormSet(self.request.POST, instance=self.object)
        if context["formset"].is_valid():
            self.object = form.save()
            context["formset"].save()
            return redirect(self.get_success_url())
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag_details_form"] = TagDetailsForm(label_suffix="", instance=self.object)
        context["metal_details_form"] = MetalDetailsForm(label_suffix="", instance=self.object)
        context["product_details_form"] = ProductDetailsForm(label_suffix="", instance=self.object)
        context["making_details_form"] = MakingDetailsForm(label_suffix="", instance=self.object)
        context["formset"] = StudFormSet(instance=self.object)
        context["stud_form"] = StudForm(label_suffix="")
        context["units"] = serializers.serialize("json", Unit.objects.all())
        context["id"] = self.object.id
        return context

stock/templates/stock/product.html
{% extends "masters/layout.html" %}
{% load static %}

{% block title %}Stock View{% endblock %}

{% block link %}
  <link rel="stylesheet" href="{% static 'stock/css/product.css' %}">
  <script src="{% static 'stock/js/product.js' %}" charset="utf-8"></script>
{% endblock %}

{% block body %}
<div id="outer-box">
  <span class="inner-text">1. Tag Details</span><!--
  --><span class="inner-text">2. Metal Details</span><!--
  --><span class="inner-text">3. Product Details</span><!--
  --><span class="inner-text">4. Making Details</span>
  <div class="inner-box" style="margin-left: 3.125vw;">
    <table class="first-row-tables">
      <tr>
        <td>Product ID</td>
        <td>{{ product.id }}</td>
      </tr>
      <tr>
        <td>Purchase Date</td>
        <td>{{ product.purchase_date |date:'d-m-Y' }}</td>
      </tr>
      <tr>
        <td>Lot No.</td>
        <td>{{ product.lot_number }}</td>
      </tr>
      <tr>
        <td>Jilaba I.D.</td>
        <td>{{ product.old_id }}</td>
      </tr>
      <tr>
        <td>Register</td>
        <td>{{ product.register_id |default_if_none:"" }}</td>
      </tr>
      <tr>
        <td>Design Code</td>
        <td>{{ product.design_code }}</td>
      </tr>
    </table>
    <div class="divider" id="divider-1">
    </div>
  </div><!--
  --><div class="inner-box">
    <table class="first-row-tables">
      <tr>
        <td>Metal</td>
        <td>{{ product.metal.metal }}</td>
      </tr>
      <tr>
        <td>Purity</td>
        <td>{{ product.purity.purity }}</td>
      </tr>
      <tr>
        <td>Type</td>
        <td>{{ product.type.type }}</td>
      </tr>
      <tr>
        <td>Category</td>
        <td>{{ product.category.category }}</td>
      </tr>
      <tr>
        <td style="padding-bottom: 8.33vh;">Description</td>
        <td style="height: 5.56vh; padding-bottom: 5.56vh; vertical-align:top;">{{ product.description }}</td>
      </tr>
    </table>
    <div class="divider" id="divider-2">
    </div>
  </div><!--
  --><div class="inner-box">
    <table class="first-row-tables">
      <tr>
        <td>Vendor Code</td>
        <td>{{ product.vendor.id }}</td>
      </tr>
      <tr>
        <td>Pieces</td>
        <td>{{ product.pieces }}</td>
      </tr>
      <tr>
        <td>Gross Weight</td>
        <td>{{ product.gross_weight }}</td>
      </tr>
      <tr>
        <td>Studding</td>
        <td>{{ product.studs_weight }}</td>
      </tr>
      <tr>
        <td>Less Weight</td>
        <td>{{product.less_weight }}</td>
      </tr>
      <tr>
        <td>Net Weight</td>
        <td>{{ product.net_weight }}</td>
      </tr>
    </table>
    <div class="divider" id="divider-3">
    </div>
  </div><!--
  --><div class="inner-box">
    <table class="first-row-tables">
      <tr>
        <td>Rate</td>
        <td>{{ product.rate }}</td>
      </tr>
      <tr>
        <td>Making Charges</td>
        <td>{{ product.making_charges }}</td>
      </tr>
      <tr>
        <td>Wastage</td>
        <td>{{ product.wastage|default_if_none:"" }}</td>
      </tr>
      <tr>
        <td>M.R.P.</td>
        <td>{{ product.mrp|default_if_none:"" }}</td>
      </tr>
      <tr>
        <td style="padding-bottom: 8.33vh;">Calculation</td>
        <td style="padding-bottom: 8.33vh;">{{ product.calculation }}</td>
      </tr>
    </table>
    <div class="divider" id="divider-4">
    </div>
  </div>
  <span class="inner-text">5. Studding Details</span>
  <div class="second-row-boxes">
    <table class="second-row-tables-thead">
      <thead>
        <tr>
          <th>#</th>
          <th>Type</th>
          <th>Less</th>
          <th>Colour</th>
          <th>Shape</th>
          <th>Quantity</th>
          <th>Weight</th>
          <th>Rate</th>
          <th>Value</th>
        </tr>
      </thead>
    </table>
    <table class="second-row-tables">
      <tbody>
        {% for stud in product.studs.all %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ stud.type }}</td>
            <td>{{ stud.less|yesno|title }}</td>
            <td>{{ stud.colour }}</td>
            <td>{{ stud.shape }}</td>
            <td>{{ stud.quantity }}</td>
            <td>{{ stud.weight }} {{ stud.unit.symbol }}</td>
            <td>{{ stud.rate }}</td>
            <td>{{ stud.value }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
  

<a href="{% url 'product_new' %}"><button id="product-new" type="submit" name="product_new">New</button></a>

<a href="{% url 'product_edit' pk=product.id %}"><button id="product-edit" type="submit" name="product_edit">Edit</button></a>

<a href="{% url 'print_tag' pk=product.id %}"><button id="print-tag" type="submit" name="print_tag">Print Tag</button></a>

<div id="bottom-nav-bar">
  <span class="bottom-nav-background"></span>
  <form action="{% url 'product_detail' pk=first_id %}" method="post">
    {% csrf_token %}
    <button id = "first" type="submit" name="first"
    {% if product.id == first_id %} disabled {% endif %}
    >First</button>
  </form>

  <form action="{% url 'product_detail' product.id|add:'-1' %}" method="post">
    {% csrf_token %}
    <button id = "previous" type="submit" name="previous"
     {% if product.id == first_id %} disabled {% endif %}
    >&#60; Prev</button>
  </form>

  <form action="{% url 'product_detail' pk=0 %}" method="post">
    {% csrf_token %}
    <input id = "id" type="number" name="id" value="{{ product.id }}" min="1" max="{{ last_id }}" required oninput="validateID(this, '{% url 'fetch_product' %}')" onclick="this.select()">
  </form>
  <span id = "slash">/</span>
  <form action="" method="get">
    {% csrf_token %}
    <input id = "last-id" type="number" name="last-id" value="{{ last_id }}" disabled>
  </form>

  <form action="{% url 'product_detail' pk=product.id|add:'1' %}" method="post">
    {% csrf_token %}
    <button id = "next" type="submit" name="next"
    {% if product.id == last_id %} disabled {% endif %}
    >Next &#62;</button>
  </form>
  <form action="{% url 'product_detail' pk=last_id %}" method="post">
    {% csrf_token %}
    <button id = "last" type="submit" name="last"
    {% if product.id == last_id %} disabled {% endif %}
    >Last</button>
  </form>
</div>
{% endblock %}

stock/templates/stock/product_form.html
{% extends "masters/layout.html" %}
{% load static %}

{% block title %} New Product {% endblock %}

{% block link %}
  <link rel="stylesheet" href="{% static 'stock/css/product_form.css' %}">
  <script src="{% static 'stock/js/product_form.js' %}" charset="utf-8"></script>
{% endblock %}

{% block body %}
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    <div id="product_form_box">
      <div class="product_form_box">
        <h1>1. Tag Details</h1>
        <div>
          <label for="id_id">ID</label>
          <input type="number" value="{{ id }}" id="id_id" readonly>
        </div>
        {{ tag_details_form.as_div }}
      </div>
      <div class="product_form_box">
        <h1>2. Metal Details</h1>
        {{ metal_details_form.as_div }}
      </div>
      <div class="product_form_box">
        <h1>3. Product Details</h1>
        {{ product_details_form.as_div }}
      </div>
      <div class="product_form_box">
        <h1>4. Making Details</h1>
        {{ making_details_form.as_div }}
        <div>
          <label for="id_calculation">Calculation</label>
          <div id="id_calculation">
            <div>
              <input type="radio" name="calculation" value="Making Charges" id="id_calculation_1" oninput="makeRequired(this)" required {% if form.calculation.value == "Making Charges" %} checked {% endif %}><label for="id_calculation_1">Making Charges</label>
            </div>
            <div>
              <input type="radio" name="calculation" value="Wastage" id="id_calculation_2" oninput="makeRequired(this)" {% if form.calculation.value == "Wastage" %} checked {% endif %}><label for="id_calculation_2">Wastage</label>
            </div>
            <div>
              <input type="radio" name="calculation" value="MRP" id="id_calculation_3" oninput="makeRequired(this)" {% if form.calculation.value == "MRP" %} checked {% endif %}><label for="id_calculation_3">MRP</label>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="studs_box">
      <h1>5. Studding Details</h1>
      <table id="studs_table">
        <thead>
          <tr>
            <th>#</th>
            <th>Type</th>
            <th>Less</th>
            <th>Colour</th>
            <th>Shape</th>
            <th>Quantity</th>
            <th>Weight</th>
            <th>Rate</th>
            <th>Value</th>
            <th></th>
          </tr>
        </thead>
        {% for stud in formset %}
        <tr>
          <td id="id_serial_number_table">{{ forloop.counter }}</td>
          <td id="id_type_table">{{ stud.instance.type }}</td>
          <td id="id_less_table">{{ stud.less.value | yesno |title }}</td>
          <td id="id_colour_table">{{ stud.colour.value }}</td>
          <td id="id_shape_table">{{ stud.shape.value }}</td>
          <td id="id_quantity_table">{{ stud.quantity.value }}</td>
          <td><p id="id_weight_table">{{ stud.weight.value }}</p> <p id="id_unit_table">{{ stud.instance.unit.symbol }}</p></td>
          <td id="id_rate_table">{{ stud.rate.value }}</td>
          <td id="id_value_table">{{ stud.value.value }}</td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteStudRow(this)"></td>
          <td hidden>
            {{ stud.as_div }}
          </td>
        </tr>
        {% endfor %}
        <tr style="display: none;">
          <td id="id_serial_number_table"></td>
          <td id="id_type_table"></td>
          <td id="id_less_table"></td>
          <td id="id_colour_table"></td>
          <td id="id_shape_table"></td>
          <td id="id_quantity_table"></td>
          <td><p id="id_weight_table"></p> <p id="id_unit_table"></p></td>
          <td id="id_rate_table"></td>
          <td id="id_value_table"></td>
          <td><img class="cross" src="{% static 'sales/svg/cross.svg' %}" onclick="deleteStudRow(this)" style="display: none;"></td>
          <td hidden>
            {{ formset.empty_form.as_div }}
          </td>
        </tr>
      </table>
  </div>

  <div id="totals_box">
    <a href="{% url 'product_detail' pk=1 %}"><button id="cancel" type="button" name="cancel">Cancel</button></a>
    <button id="save" type="submit" name="save">Save</button>
  </div>
  </form>

  <div id="studs_subform_box">
    <button type="button" class="new_button" id="stud_new" onclick="newStudRow(this)">New</button>
    <form action="javascript: submitStudRow(this)" id="studs_subform" hidden>
      <div id="stud_subform">
        {{ stud_form.as_div }}
      </div>
      <button type="reset" class="clear_button" id="stud_clear">Clear</button>
      <button type="submit" class="submit_button" id="stud_submit">Submit</button>
    </form>
  </div>

{% endblock %}